on: [push, pull_request]

name: Clippy check

permissions:
    checks: write

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@1.7.1.1
        with:
          components: clippy
      - uses: auguwu/clippy-action@1.2.1
        with:
            token: ${{secrets.GITHUB_TOKEN}}
